#! /usr/bin/python3.6

import rospy
from std_msgs.msg import Float32MultiArray, MultiArrayDimension, Float32
import serial
import threading, time
from time import sleep
from math import *
from calculate import massMathMotorCalculateAngle
import os

class main():
    point_li = []
    gps_li = [0,0]
    imu_value = 0
    docking_value = [90,90]
    stop = False

    rospy.init_node('main', anonymous = True)
    pub = rospy.Publisher('motor_list', Float32MultiArray, queue_size = 1)
    msg  = Float32MultiArray()

    
    def __init__(self):
        rospy.init_node('main', anonymous = True)
        stackDataFileName = 'Alldata.txt'
        self.f = open(stackDataFileName, 'w')
        self.input_point()
        
        
    def input_point(self):
        self.point_li = [[35.5448432,129.2518805],[35.5448740,129.2519252],[355448499.0, 1292518389.0]]
        self.motor_Calculator = massMathMotorCalculateAngle(self.point_li)
        
        print("gps , imu thread start")
        while not rospy.is_shutdown():
              self.gps_listener()
              self.imu_listener()
              answer = self.motor_calculate()
              if answer == "finish":
                  break
              sleep(0.5)
        os.system("python3 docking.py")
        while not rospy.is_shutdown():
              docking_listener()
              docking_answer = self.motor_docking()
              if docking_answer == "finish":
                  break
              sleep(0.5)

        
    
    def motor_calculate(self):
        if self.stop == False:
            motor_value = self.motor_Calculator.RealWhileAllMethod(self.gps_li, self.imu_value)
            if motor_value == "finish":
                motor_value = [90,90]
                self.msg.data = motor_value
                self.pub.publish(self.msg)
                return "finish"
            self.msg.data = motor_value
            self.pub.publish(self.msg)
            print(self.gps_li)
            print(self.imu_value)
            print("motorValue: {}".format(motor_value))

    def motor_docking(self):
        self.msg.data = docking_value
        self.pub.publish(self.msg)
        print("motorValue: {}".format(docking_value))

        
            
    def gps_callback(self, data):
        self.gps_li = [data.data[0]*0.0000001, data.data[1]*0.0000001]
        
    def gps_listener(self):
        rospy.Subscriber('gps_list', Float32MultiArray, self.gps_callback)
        
    def imu_callback(self,data):
        self.imu_value = data.data
        
    def imu_listener(self):
        rospy.Subscriber('imu_list', Float32, self.imu_callback)

    def docking_callback(self,data):
        self.docking_value = data.data
        
    def docking_listener(self):
        rospy.Subscriber('docking_list', Float32MultiArray, self.docking_callback)



if __name__ == '__main__':
    try:
        hopp = main()
    except rospy.ROSInterruptException:
        pass
